ignored:
  - DL3002 #learning: it's ok to be root sometimes
  - DL3003 #ignore that we use cd sometimes
  - DL3006 #image pin versions
  - DL3008 #apt pin versions
  - DL3012 #learning: multiple HEALTHCHECKs ok
  - DL3016 # npm pin versions
  - DL3018 #apk add pin versions
  - DL3022 #bad rule for COPY --from
  - DL3028 #gem install pin versions
  - DL3059 #multiple consecutive runs
  - DL4006 #we don't need pipefail in this
  - SC2016 #we want single quotes sometimes