# version no longer needed
services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    # strapi v3 doesn't build on arm64 yet. Hardcode to amd64 (x86_64) for now
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - 3030:1337
    # override the Dockerfile CMD for local development
    command: strapi start
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - NODE_ENV=development

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=strapi

volumes:
  mongo:
